// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

void ui_event_comp_ScreenButtons_Home_ImgButtonHome(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ScreenButtons = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Home, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Home_screen_init);
    }
}

void ui_event_comp_ScreenButtons_Home_ImgButtonSetvalues(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ScreenButtons = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_SetValues, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_SetValues_screen_init);
    }
}

void ui_event_comp_ScreenButtons_Home_ImgButtonSettings(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t ** comp_ScreenButtons = lv_event_get_user_data(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Settings, LV_SCR_LOAD_ANIM_FADE_ON, 10, 0, &ui_Settings_screen_init);
    }
}

// COMPONENT ScreenButtons

lv_obj_t * ui_ScreenButtons_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_ScreenButtons;
    cui_ScreenButtons = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_ScreenButtons, lv_pct(98));
    lv_obj_set_height(cui_ScreenButtons, lv_pct(15));
    lv_obj_set_x(cui_ScreenButtons, 0);
    lv_obj_set_y(cui_ScreenButtons, -2);
    lv_obj_set_align(cui_ScreenButtons, LV_ALIGN_BOTTOM_MID);
    lv_obj_set_flex_flow(cui_ScreenButtons, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_ScreenButtons, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_clear_flag(cui_ScreenButtons, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_ScreenButtons, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(cui_ScreenButtons, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_t * cui_Home_ImgButtonHome;
    cui_Home_ImgButtonHome = lv_imgbtn_create(cui_ScreenButtons);
    lv_imgbtn_set_src(cui_Home_ImgButtonHome, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_home_copy_png, NULL);
    lv_imgbtn_set_src(cui_Home_ImgButtonHome, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_home_copy_png, NULL);
    lv_obj_set_width(cui_Home_ImgButtonHome, 50);
    lv_obj_set_height(cui_Home_ImgButtonHome, 50);
    lv_obj_set_align(cui_Home_ImgButtonHome, LV_ALIGN_CENTER);

    lv_obj_t * cui_Home_ImgButtonSetvalues;
    cui_Home_ImgButtonSetvalues = lv_imgbtn_create(cui_ScreenButtons);
    lv_imgbtn_set_src(cui_Home_ImgButtonSetvalues, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_setvalues_copy_png, NULL);
    lv_imgbtn_set_src(cui_Home_ImgButtonSetvalues, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_setvalues_copy_png, NULL);
    lv_obj_set_width(cui_Home_ImgButtonSetvalues, 50);
    lv_obj_set_height(cui_Home_ImgButtonSetvalues, 50);
    lv_obj_set_align(cui_Home_ImgButtonSetvalues, LV_ALIGN_CENTER);

    lv_obj_t * cui_Home_ImgButtonSettings;
    cui_Home_ImgButtonSettings = lv_imgbtn_create(cui_ScreenButtons);
    lv_imgbtn_set_src(cui_Home_ImgButtonSettings, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_settings_copy_png, NULL);
    lv_imgbtn_set_src(cui_Home_ImgButtonSettings, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_settings_copy_png, NULL);
    lv_obj_set_width(cui_Home_ImgButtonSettings, 50);
    lv_obj_set_height(cui_Home_ImgButtonSettings, 50);
    lv_obj_set_align(cui_Home_ImgButtonSettings, LV_ALIGN_CENTER);

    lv_obj_t ** children = lv_mem_alloc(sizeof(lv_obj_t *) * _UI_COMP_SCREENBUTTONS_NUM);
    children[UI_COMP_SCREENBUTTONS_SCREENBUTTONS] = cui_ScreenButtons;
    children[UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONHOME] = cui_Home_ImgButtonHome;
    children[UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONSETVALUES] = cui_Home_ImgButtonSetvalues;
    children[UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONSETTINGS] = cui_Home_ImgButtonSettings;
    lv_obj_add_event_cb(cui_ScreenButtons, get_component_child_event_cb, LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_ScreenButtons, del_component_child_event_cb, LV_EVENT_DELETE, children);
    lv_obj_add_event_cb(cui_Home_ImgButtonHome, ui_event_comp_ScreenButtons_Home_ImgButtonHome, LV_EVENT_ALL, children);
    lv_obj_add_event_cb(cui_Home_ImgButtonSetvalues, ui_event_comp_ScreenButtons_Home_ImgButtonSetvalues, LV_EVENT_ALL,
                        children);
    lv_obj_add_event_cb(cui_Home_ImgButtonSettings, ui_event_comp_ScreenButtons_Home_ImgButtonSettings, LV_EVENT_ALL,
                        children);
    ui_comp_ScreenButtons_create_hook(cui_ScreenButtons);
    return cui_ScreenButtons;
}

