// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_COMP_SCREENBUTTONS_H
#define _UI_COMP_SCREENBUTTONS_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT ScreenButtons
#define UI_COMP_SCREENBUTTONS_SCREENBUTTONS 0
#define UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONHOME 1
#define UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONSETVALUES 2
#define UI_COMP_SCREENBUTTONS_HOME_IMGBUTTONSETTINGS 3
#define _UI_COMP_SCREENBUTTONS_NUM 4
lv_obj_t * ui_ScreenButtons_create(lv_obj_t * comp_parent);
void ui_event_comp_ScreenButtons_Home_ImgButtonHome(lv_event_t * e);
void ui_event_comp_ScreenButtons_Home_ImgButtonSetvalues(lv_event_t * e);
void ui_event_comp_ScreenButtons_Home_ImgButtonSettings(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
