// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t * uic_Settings_LabelResetEnergy;
lv_obj_t * uic_Settings_ButtonResetEnergy;
lv_obj_t * uic_Settings_LabelBrightness;
lv_obj_t * uic_Settings_SliderBrightness;
lv_obj_t * uic_Settings_TextAreaLogs;
lv_obj_t * uic_Settings_DropdownFanControll;
lv_obj_t * uic_Settings;
lv_obj_t * ui_Settings = NULL;
lv_obj_t * ui_ScreenButtons3 = NULL;
lv_obj_t * ui_Settings_DropdownFanControll = NULL;
lv_obj_t * ui_Settings_TextAreaLogs = NULL;
lv_obj_t * ui_Settings_Label3 = NULL;
lv_obj_t * ui_Settings_Label1 = NULL;
lv_obj_t * ui_Settings_TextAreaSleep = NULL;
lv_obj_t * ui_Numpad2 = NULL;
lv_obj_t * ui_Settings_SliderBrightness = NULL;
lv_obj_t * ui_Settings_LabelBrightness = NULL;
lv_obj_t * ui_Settings_ButtonResetEnergy = NULL;
lv_obj_t * ui_Settings_LabelResetEnergy = NULL;
// event funtions
void ui_event_Settings_TextAreaSleep(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_flag_modify(ui_Numpad2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
        _ui_keyboard_set_target(ui_Numpad2,  ui_Settings_TextAreaSleep);
    }
}

void ui_event_Numpad2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_READY) {
        _ui_flag_modify(ui_Numpad2, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_Settings_SliderBrightness(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Settings_LabelBrightness, target, "", "%");
    }
}

// build funtions

void ui_Settings_screen_init(void)
{
    ui_Settings = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Settings, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_ScreenButtons3 = ui_ScreenButtons_create(ui_Settings);
    lv_obj_set_x(ui_ScreenButtons3, 0);
    lv_obj_set_y(ui_ScreenButtons3, -2);

    ui_Settings_DropdownFanControll = lv_dropdown_create(ui_Settings);
    lv_dropdown_set_options(ui_Settings_DropdownFanControll, "FAN AUTO\nFAN FULL POWER");
    lv_obj_set_width(ui_Settings_DropdownFanControll, lv_pct(98));
    lv_obj_set_height(ui_Settings_DropdownFanControll, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Settings_DropdownFanControll, LV_ALIGN_TOP_MID);
    lv_obj_add_flag(ui_Settings_DropdownFanControll, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_set_style_text_font(ui_Settings_DropdownFanControll, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings_DropdownFanControll, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings_DropdownFanControll, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_text_font(lv_dropdown_get_list(ui_Settings_DropdownFanControll), &lv_font_montserrat_20,
                               LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(lv_dropdown_get_list(ui_Settings_DropdownFanControll), lv_color_hex(0xFFFFFF),
                                  LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(lv_dropdown_get_list(ui_Settings_DropdownFanControll), 255,
                                LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_TextAreaLogs = lv_textarea_create(ui_Settings);
    lv_obj_set_height(ui_Settings_TextAreaLogs, 211);
    lv_obj_set_width(ui_Settings_TextAreaLogs, lv_pct(98));
    lv_obj_set_x(ui_Settings_TextAreaLogs, 0);
    lv_obj_set_y(ui_Settings_TextAreaLogs, -77);
    lv_obj_set_align(ui_Settings_TextAreaLogs, LV_ALIGN_BOTTOM_MID);
    lv_textarea_set_placeholder_text(ui_Settings_TextAreaLogs, "LOGS");
    lv_obj_set_style_text_font(ui_Settings_TextAreaLogs, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_Label3 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Settings_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Label3, 6);
    lv_obj_set_y(ui_Settings_Label3, -181);
    lv_obj_set_align(ui_Settings_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Label3, "DISPLAY BRIGHTNESS");

    ui_Settings_Label1 = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Settings_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_Label1, -110);
    lv_obj_set_y(ui_Settings_Label1, -120);
    lv_obj_set_align(ui_Settings_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_Label1, "SLEEP [S]");

    ui_Settings_TextAreaSleep = lv_textarea_create(ui_Settings);
    lv_obj_set_width(ui_Settings_TextAreaSleep, lv_pct(19));
    lv_obj_set_height(ui_Settings_TextAreaSleep, LV_SIZE_CONTENT);    /// 70
    lv_obj_set_x(ui_Settings_TextAreaSleep, -110);
    lv_obj_set_y(ui_Settings_TextAreaSleep, -90);
    lv_obj_set_align(ui_Settings_TextAreaSleep, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_Settings_TextAreaSleep, "30");
    lv_textarea_set_one_line(ui_Settings_TextAreaSleep, true);
    lv_obj_set_style_text_font(ui_Settings_TextAreaSleep, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);
    ui_object_set_themeable_style_property(ui_Settings_TextAreaSleep, LV_PART_MAIN | LV_STATE_DEFAULT,
                                           LV_STYLE_BORDER_COLOR, _ui_theme_color_BorderColorWidge);
    ui_object_set_themeable_style_property(ui_Settings_TextAreaSleep, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA,
                                           _ui_theme_alpha_BorderColorWidge);

    ui_Numpad2 = lv_keyboard_create(ui_Settings);
    lv_keyboard_set_mode(ui_Numpad2, LV_KEYBOARD_MODE_NUMBER);
    lv_obj_set_height(ui_Numpad2, 217);
    lv_obj_set_width(ui_Numpad2, lv_pct(98));
    lv_obj_set_x(ui_Numpad2, 0);
    lv_obj_set_y(ui_Numpad2, -74);
    lv_obj_set_align(ui_Numpad2, LV_ALIGN_BOTTOM_MID);
    lv_obj_add_flag(ui_Numpad2, LV_OBJ_FLAG_HIDDEN);     /// Flags

    lv_obj_set_style_radius(ui_Numpad2, 10, LV_PART_ITEMS | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Numpad2, &lv_font_montserrat_20, LV_PART_ITEMS | LV_STATE_DEFAULT);

    ui_Settings_SliderBrightness = lv_slider_create(ui_Settings);
    lv_slider_set_value(ui_Settings_SliderBrightness, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Settings_SliderBrightness) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(
            ui_Settings_SliderBrightness, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_Settings_SliderBrightness, 10);
    lv_obj_set_width(ui_Settings_SliderBrightness, lv_pct(73));
    lv_obj_set_x(ui_Settings_SliderBrightness, -15);
    lv_obj_set_y(ui_Settings_SliderBrightness, -160);
    lv_obj_set_align(ui_Settings_SliderBrightness, LV_ALIGN_RIGHT_MID);
    lv_obj_set_style_bg_color(ui_Settings_SliderBrightness, lv_color_hex(0x252525), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_SliderBrightness, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Settings_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Settings_SliderBrightness, LV_GRAD_DIR_HOR, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Settings_SliderBrightness, lv_color_hex(0x252525), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_SliderBrightness, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_Settings_SliderBrightness, lv_color_hex(0xFFFFFF),
                                   LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_Settings_SliderBrightness, LV_GRAD_DIR_HOR, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Settings_SliderBrightness, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_SliderBrightness, 255, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Settings_LabelBrightness = lv_label_create(ui_Settings);
    lv_obj_set_width(ui_Settings_LabelBrightness, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_LabelBrightness, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Settings_LabelBrightness, -123);
    lv_obj_set_y(ui_Settings_LabelBrightness, -161);
    lv_obj_set_align(ui_Settings_LabelBrightness, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_LabelBrightness, "50%");
    lv_obj_set_style_text_font(ui_Settings_LabelBrightness, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_ButtonResetEnergy = lv_btn_create(ui_Settings);
    lv_obj_set_width(ui_Settings_ButtonResetEnergy, 152);
    lv_obj_set_height(ui_Settings_ButtonResetEnergy, 39);
    lv_obj_set_x(ui_Settings_ButtonResetEnergy, 71);
    lv_obj_set_y(ui_Settings_ButtonResetEnergy, -92);
    lv_obj_set_align(ui_Settings_ButtonResetEnergy, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Settings_ButtonResetEnergy, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Settings_ButtonResetEnergy, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Settings_ButtonResetEnergy, lv_color_hex(0x101418), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Settings_ButtonResetEnergy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Settings_ButtonResetEnergy, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Settings_ButtonResetEnergy, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Settings_ButtonResetEnergy, 2, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Settings_LabelResetEnergy = lv_label_create(ui_Settings_ButtonResetEnergy);
    lv_obj_set_width(ui_Settings_LabelResetEnergy, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Settings_LabelResetEnergy, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Settings_LabelResetEnergy, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Settings_LabelResetEnergy, "RESET ENERGY");
    lv_obj_set_style_text_font(ui_Settings_LabelResetEnergy, &lv_font_montserrat_18, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Settings_TextAreaSleep, ui_event_Settings_TextAreaSleep, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Numpad2, ui_event_Numpad2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Settings_SliderBrightness, ui_event_Settings_SliderBrightness, LV_EVENT_ALL, NULL);
    uic_Settings = ui_Settings;
    uic_Settings_DropdownFanControll = ui_Settings_DropdownFanControll;
    uic_Settings_TextAreaLogs = ui_Settings_TextAreaLogs;
    uic_Settings_SliderBrightness = ui_Settings_SliderBrightness;
    uic_Settings_LabelBrightness = ui_Settings_LabelBrightness;
    uic_Settings_ButtonResetEnergy = ui_Settings_ButtonResetEnergy;
    uic_Settings_LabelResetEnergy = ui_Settings_LabelResetEnergy;

}

void ui_Settings_screen_destroy(void)
{
    if(ui_Settings) lv_obj_del(ui_Settings);

    // NULL screen variables
    uic_Settings = NULL;
    ui_Settings = NULL;
    ui_ScreenButtons3 = NULL;
    uic_Settings_DropdownFanControll = NULL;
    ui_Settings_DropdownFanControll = NULL;
    uic_Settings_TextAreaLogs = NULL;
    ui_Settings_TextAreaLogs = NULL;
    ui_Settings_Label3 = NULL;
    ui_Settings_Label1 = NULL;
    ui_Settings_TextAreaSleep = NULL;
    ui_Numpad2 = NULL;
    uic_Settings_SliderBrightness = NULL;
    ui_Settings_SliderBrightness = NULL;
    uic_Settings_LabelBrightness = NULL;
    ui_Settings_LabelBrightness = NULL;
    uic_Settings_ButtonResetEnergy = NULL;
    ui_Settings_ButtonResetEnergy = NULL;
    uic_Settings_LabelResetEnergy = NULL;
    ui_Settings_LabelResetEnergy = NULL;

}
