// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t * ui_Settings;
extern lv_obj_t * ui_ScreenButtons3;
extern lv_obj_t * ui_Settings_DropdownFanControll;
extern lv_obj_t * ui_Settings_TextAreaLogs;
extern lv_obj_t * ui_Settings_Label3;
extern lv_obj_t * ui_Settings_Label1;
extern void ui_event_Settings_TextAreaSleep(lv_event_t * e);
extern lv_obj_t * ui_Settings_TextAreaSleep;
extern void ui_event_Numpad2(lv_event_t * e);
extern lv_obj_t * ui_Numpad2;
extern void ui_event_Settings_SliderBrightness(lv_event_t * e);
extern lv_obj_t * ui_Settings_SliderBrightness;
extern lv_obj_t * ui_Settings_LabelBrightness;
extern lv_obj_t * ui_Settings_ButtonResetEnergy;
extern lv_obj_t * ui_Settings_LabelResetEnergy;
// CUSTOM VARIABLES
extern lv_obj_t * uic_Settings;
extern lv_obj_t * uic_Settings_DropdownFanControll;
extern lv_obj_t * uic_Settings_TextAreaLogs;
extern lv_obj_t * uic_Settings_SliderBrightness;
extern lv_obj_t * uic_Settings_LabelBrightness;
extern lv_obj_t * uic_Settings_ButtonResetEnergy;
extern lv_obj_t * uic_Settings_LabelResetEnergy;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

