// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
  #if __has_include("lvgl.h")
    #include "lvgl.h"
  #elif __has_include("lvgl/lvgl.h")
    #include "lvgl/lvgl.h"
  #else
    #include "lvgl.h"
  #endif
#else
  #include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

///////////////////// SCREENS ////////////////////
#include "ui_Home.h"
#include "ui_SetValues.h"
#include "ui_Settings.h"
#include "ui_Connectivity.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE( ui_img_home_copy_png);   // assets/home copy.png
LV_IMG_DECLARE( ui_img_setvalues_copy_png);   // assets/SetValues copy.png
LV_IMG_DECLARE( ui_img_settings_copy_png);   // assets/settings copy.png
LV_IMG_DECLARE( ui_img_connectivity_copy_png);   // assets/connectivity copy.png
LV_IMG_DECLARE( ui_img_bin_45x45_png);   // assets/bin 45x45.png
LV_IMG_DECLARE( ui_img_link_45x45_png);   // assets/link 45x45.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
