// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Connectivity_Keyboard;
lv_obj_t *uic_Connectivity_TextAreaNetworkLog;
lv_obj_t *uic_Connectivity_TextAreaPassword;
lv_obj_t *uic_Connectivity_TextAreaSSID;
lv_obj_t *uic_Connectivity;
lv_obj_t *ui_Connectivity = NULL;lv_obj_t *ui_ScreenButtons4 = NULL;lv_obj_t *ui_Connectivity_TextAreaSSID = NULL;lv_obj_t *ui_Connectivity_TextAreaPassword = NULL;lv_obj_t *ui_Connectivity_TextAreaNetworkLog = NULL;lv_obj_t *ui_Connectivity_Keyboard = NULL;
// event funtions
void ui_event_Connectivity_TextAreaSSID( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Connectivity_Keyboard,  ui_Connectivity_TextAreaSSID);
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Connectivity_TextAreaPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Connectivity_Keyboard,  ui_Connectivity_TextAreaPassword);
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Connectivity_Keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_Connectivity_screen_init(void)
{
ui_Connectivity = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Connectivity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenButtons4 = ui_ScreenButtons_create(ui_Connectivity);
lv_obj_set_x( ui_ScreenButtons4, 0 );
lv_obj_set_y( ui_ScreenButtons4, -2 );

ui_Connectivity_TextAreaSSID = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaSSID, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaSSID, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Connectivity_TextAreaSSID, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaSSID, 3 );
lv_obj_set_align( ui_Connectivity_TextAreaSSID, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_Connectivity_TextAreaSSID,"Enter netwrok SSID");
lv_textarea_set_one_line(ui_Connectivity_TextAreaSSID,true);
lv_obj_set_style_text_font(ui_Connectivity_TextAreaSSID, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Connectivity_TextAreaPassword = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaPassword, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaPassword, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Connectivity_TextAreaPassword, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaPassword, 47 );
lv_obj_set_align( ui_Connectivity_TextAreaPassword, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_Connectivity_TextAreaPassword,"Enter netwrok Password");
lv_textarea_set_one_line(ui_Connectivity_TextAreaPassword,true);
lv_obj_set_style_text_font(ui_Connectivity_TextAreaPassword, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Connectivity_TextAreaNetworkLog = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaNetworkLog, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaNetworkLog, lv_pct(63));
lv_obj_set_x( ui_Connectivity_TextAreaNetworkLog, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaNetworkLog, -85 );
lv_obj_set_align( ui_Connectivity_TextAreaNetworkLog, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_text(ui_Connectivity_TextAreaNetworkLog,"Enter the network SSID and password. Then visit the xxx.xxx.xx.xx IP-address to control the device using a PC");
lv_textarea_set_placeholder_text(ui_Connectivity_TextAreaNetworkLog,"Network Log");

ui_Connectivity_Keyboard = lv_keyboard_create(ui_Connectivity);
lv_obj_set_height( ui_Connectivity_Keyboard, 170);
lv_obj_set_width( ui_Connectivity_Keyboard, lv_pct(100));
lv_obj_set_x( ui_Connectivity_Keyboard, 0 );
lv_obj_set_y( ui_Connectivity_Keyboard, -75 );
lv_obj_set_align( ui_Connectivity_Keyboard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_Connectivity_Keyboard, &lv_font_montserrat_18, LV_PART_ITEMS| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_Connectivity_TextAreaSSID, ui_event_Connectivity_TextAreaSSID, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Connectivity_TextAreaPassword, ui_event_Connectivity_TextAreaPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Connectivity_Keyboard, ui_event_Connectivity_Keyboard, LV_EVENT_ALL, NULL);
uic_Connectivity = ui_Connectivity;
uic_Connectivity_TextAreaSSID = ui_Connectivity_TextAreaSSID;
uic_Connectivity_TextAreaPassword = ui_Connectivity_TextAreaPassword;
uic_Connectivity_TextAreaNetworkLog = ui_Connectivity_TextAreaNetworkLog;
uic_Connectivity_Keyboard = ui_Connectivity_Keyboard;

}

void ui_Connectivity_screen_destroy(void)
{
   if (ui_Connectivity) lv_obj_del(ui_Connectivity);

// NULL screen variables
uic_Connectivity= NULL;
ui_Connectivity= NULL;
ui_ScreenButtons4= NULL;
uic_Connectivity_TextAreaSSID= NULL;
ui_Connectivity_TextAreaSSID= NULL;
uic_Connectivity_TextAreaPassword= NULL;
ui_Connectivity_TextAreaPassword= NULL;
uic_Connectivity_TextAreaNetworkLog= NULL;
ui_Connectivity_TextAreaNetworkLog= NULL;
uic_Connectivity_Keyboard= NULL;
ui_Connectivity_Keyboard= NULL;

}
