// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_CONNECTIVITY_H
#define UI_CONNECTIVITY_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Connectivity
extern void ui_Connectivity_screen_init(void);
extern void ui_Connectivity_screen_destroy(void);
extern lv_obj_t *ui_Connectivity;
extern lv_obj_t *ui_ScreenButtons4;
extern void ui_event_Connectivity_TextAreaSSID( lv_event_t * e);
extern lv_obj_t *ui_Connectivity_TextAreaSSID;
extern void ui_event_Connectivity_TextAreaPassword( lv_event_t * e);
extern lv_obj_t *ui_Connectivity_TextAreaPassword;
extern lv_obj_t *ui_Connectivity_TextAreaNetworkLog;
extern void ui_event_Connectivity_Keyboard( lv_event_t * e);
extern lv_obj_t *ui_Connectivity_Keyboard;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Connectivity;
extern lv_obj_t *uic_Connectivity_TextAreaSSID;
extern lv_obj_t *uic_Connectivity_TextAreaPassword;
extern lv_obj_t *uic_Connectivity_TextAreaNetworkLog;
extern lv_obj_t *uic_Connectivity_Keyboard;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

