// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_Connectivity_ImgButtonConnectNetwork;
lv_obj_t *uic_Connectivity_ImgButtonDeleteNetwork;
lv_obj_t *uic_Connectivity_DropdownSavednetworks;
lv_obj_t *uic_Connectivity_Keyboard;
lv_obj_t *uic_Connectivity_TextAreaNetworkLog;
lv_obj_t *uic_Connectivity_TextAreaPassword;
lv_obj_t *uic_Connectivity_TextAreaSSID;
lv_obj_t *uic_Connectivity;
lv_obj_t *ui_Connectivity = NULL;lv_obj_t *ui_ScreenButtons4 = NULL;lv_obj_t *ui_Connectivity_TextAreaSSID = NULL;lv_obj_t *ui_Connectivity_TextAreaPassword = NULL;lv_obj_t *ui_Connectivity_TextAreaNetworkLog = NULL;lv_obj_t *ui_Connectivity_Keyboard = NULL;lv_obj_t *ui_Connectivity_DropdownSavednetworks = NULL;lv_obj_t *ui_Connectivity_ImgButtonDeleteNetwork = NULL;lv_obj_t *ui_Connectivity_ImgButtonConnectNetwork = NULL;
// event funtions
void ui_event_Connectivity_TextAreaSSID( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Connectivity_Keyboard,  ui_Connectivity_TextAreaSSID);
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Connectivity_TextAreaPassword( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Connectivity_Keyboard,  ui_Connectivity_TextAreaPassword);
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Connectivity_Keyboard( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

// build funtions

void ui_Connectivity_screen_init(void)
{
ui_Connectivity = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Connectivity, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenButtons4 = ui_ScreenButtons_create(ui_Connectivity);
lv_obj_set_x( ui_ScreenButtons4, 0 );
lv_obj_set_y( ui_ScreenButtons4, -2 );

ui_Connectivity_TextAreaSSID = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaSSID, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaSSID, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Connectivity_TextAreaSSID, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaSSID, 3 );
lv_obj_set_align( ui_Connectivity_TextAreaSSID, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_Connectivity_TextAreaSSID,"Enter netwrok SSID");
lv_textarea_set_one_line(ui_Connectivity_TextAreaSSID,true);
lv_obj_set_style_text_font(ui_Connectivity_TextAreaSSID, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Connectivity_TextAreaPassword = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaPassword, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaPassword, LV_SIZE_CONTENT);   /// 37
lv_obj_set_x( ui_Connectivity_TextAreaPassword, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaPassword, 47 );
lv_obj_set_align( ui_Connectivity_TextAreaPassword, LV_ALIGN_TOP_MID );
lv_textarea_set_placeholder_text(ui_Connectivity_TextAreaPassword,"Enter netwrok Password");
lv_textarea_set_one_line(ui_Connectivity_TextAreaPassword,true);
lv_obj_set_style_text_font(ui_Connectivity_TextAreaPassword, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Connectivity_TextAreaNetworkLog = lv_textarea_create(ui_Connectivity);
lv_obj_set_width( ui_Connectivity_TextAreaNetworkLog, lv_pct(98));
lv_obj_set_height( ui_Connectivity_TextAreaNetworkLog, lv_pct(42));
lv_obj_set_x( ui_Connectivity_TextAreaNetworkLog, 0 );
lv_obj_set_y( ui_Connectivity_TextAreaNetworkLog, -77 );
lv_obj_set_align( ui_Connectivity_TextAreaNetworkLog, LV_ALIGN_BOTTOM_MID );

ui_Connectivity_Keyboard = lv_keyboard_create(ui_Connectivity);
lv_obj_set_height( ui_Connectivity_Keyboard, 170);
lv_obj_set_width( ui_Connectivity_Keyboard, lv_pct(100));
lv_obj_set_x( ui_Connectivity_Keyboard, 0 );
lv_obj_set_y( ui_Connectivity_Keyboard, -75 );
lv_obj_set_align( ui_Connectivity_Keyboard, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Connectivity_Keyboard, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_text_font(ui_Connectivity_Keyboard, &lv_font_montserrat_18, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_Connectivity_DropdownSavednetworks = lv_dropdown_create(ui_Connectivity);
lv_dropdown_set_options( ui_Connectivity_DropdownSavednetworks, "Network 1\nNetwork 2\nNetwork 3" );
lv_obj_set_width( ui_Connectivity_DropdownSavednetworks, lv_pct(98));
lv_obj_set_height( ui_Connectivity_DropdownSavednetworks, lv_pct(8));
lv_obj_set_x( ui_Connectivity_DropdownSavednetworks, 0 );
lv_obj_set_y( ui_Connectivity_DropdownSavednetworks, -130 );
lv_obj_set_align( ui_Connectivity_DropdownSavednetworks, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Connectivity_DropdownSavednetworks, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags

ui_Connectivity_ImgButtonDeleteNetwork = lv_imgbtn_create(ui_Connectivity);
lv_imgbtn_set_src(ui_Connectivity_ImgButtonDeleteNetwork, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_bin_45x45_png, NULL);
lv_imgbtn_set_src(ui_Connectivity_ImgButtonDeleteNetwork, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_bin_45x45_png, NULL);
lv_obj_set_width( ui_Connectivity_ImgButtonDeleteNetwork, 45);
lv_obj_set_height( ui_Connectivity_ImgButtonDeleteNetwork, 45);
lv_obj_set_x( ui_Connectivity_ImgButtonDeleteNetwork, -60 );
lv_obj_set_y( ui_Connectivity_ImgButtonDeleteNetwork, -70 );
lv_obj_set_align( ui_Connectivity_ImgButtonDeleteNetwork, LV_ALIGN_CENTER );
lv_obj_set_style_transform_zoom(ui_Connectivity_ImgButtonDeleteNetwork, 200, LV_PART_MAIN| LV_STATE_PRESSED);

ui_Connectivity_ImgButtonConnectNetwork = lv_imgbtn_create(ui_Connectivity);
lv_imgbtn_set_src(ui_Connectivity_ImgButtonConnectNetwork, LV_IMGBTN_STATE_RELEASED, NULL, &ui_img_link_45x45_png, NULL);
lv_imgbtn_set_src(ui_Connectivity_ImgButtonConnectNetwork, LV_IMGBTN_STATE_PRESSED, NULL, &ui_img_link_45x45_png, NULL);
lv_obj_set_width( ui_Connectivity_ImgButtonConnectNetwork, 45);
lv_obj_set_height( ui_Connectivity_ImgButtonConnectNetwork, 45);
lv_obj_set_x( ui_Connectivity_ImgButtonConnectNetwork, 60 );
lv_obj_set_y( ui_Connectivity_ImgButtonConnectNetwork, -70 );
lv_obj_set_align( ui_Connectivity_ImgButtonConnectNetwork, LV_ALIGN_CENTER );
lv_obj_set_style_transform_zoom(ui_Connectivity_ImgButtonConnectNetwork, 200, LV_PART_MAIN| LV_STATE_PRESSED);

lv_obj_add_event_cb(ui_Connectivity_TextAreaSSID, ui_event_Connectivity_TextAreaSSID, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Connectivity_TextAreaPassword, ui_event_Connectivity_TextAreaPassword, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Connectivity_Keyboard, ui_event_Connectivity_Keyboard, LV_EVENT_ALL, NULL);
uic_Connectivity = ui_Connectivity;
uic_Connectivity_TextAreaSSID = ui_Connectivity_TextAreaSSID;
uic_Connectivity_TextAreaPassword = ui_Connectivity_TextAreaPassword;
uic_Connectivity_TextAreaNetworkLog = ui_Connectivity_TextAreaNetworkLog;
uic_Connectivity_Keyboard = ui_Connectivity_Keyboard;
uic_Connectivity_DropdownSavednetworks = ui_Connectivity_DropdownSavednetworks;
uic_Connectivity_ImgButtonDeleteNetwork = ui_Connectivity_ImgButtonDeleteNetwork;
uic_Connectivity_ImgButtonConnectNetwork = ui_Connectivity_ImgButtonConnectNetwork;

}

void ui_Connectivity_screen_destroy(void)
{
   if (ui_Connectivity) lv_obj_del(ui_Connectivity);

// NULL screen variables
uic_Connectivity= NULL;
ui_Connectivity= NULL;
ui_ScreenButtons4= NULL;
uic_Connectivity_TextAreaSSID= NULL;
ui_Connectivity_TextAreaSSID= NULL;
uic_Connectivity_TextAreaPassword= NULL;
ui_Connectivity_TextAreaPassword= NULL;
uic_Connectivity_TextAreaNetworkLog= NULL;
ui_Connectivity_TextAreaNetworkLog= NULL;
uic_Connectivity_Keyboard= NULL;
ui_Connectivity_Keyboard= NULL;
uic_Connectivity_DropdownSavednetworks= NULL;
ui_Connectivity_DropdownSavednetworks= NULL;
uic_Connectivity_ImgButtonDeleteNetwork= NULL;
ui_Connectivity_ImgButtonDeleteNetwork= NULL;
uic_Connectivity_ImgButtonConnectNetwork= NULL;
ui_Connectivity_ImgButtonConnectNetwork= NULL;

}
