// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Home
extern void ui_Home_screen_init(void);
extern void ui_Home_screen_destroy(void);
extern lv_obj_t *ui_Home;
extern lv_obj_t *ui_HomePanl1;
extern lv_obj_t *ui_Home_PanelOutputEnable;
extern void ui_event_Home_SwitchEnableOutput( lv_event_t * e);
extern lv_obj_t *ui_Home_SwitchEnableOutput;
extern lv_obj_t *ui_VarOutputState;
extern lv_obj_t *ui_PanlOutput;
extern lv_obj_t *ui_Output;
extern lv_obj_t *ui_ContVout;
extern lv_obj_t *ui_LabVout;
extern lv_obj_t *ui_VarVout;
extern lv_obj_t *ui_UniVout;
extern lv_obj_t *ui_ContIout;
extern lv_obj_t *ui_LabIout;
extern lv_obj_t *ui_VarIout;
extern lv_obj_t *ui_UniIout;
extern lv_obj_t *ui_ContPout;
extern lv_obj_t *ui_LabPout;
extern lv_obj_t *ui_VarPout;
extern lv_obj_t *ui_UniPout;
extern lv_obj_t *ui_ContEnergy;
extern lv_obj_t *ui_LabEnergy;
extern lv_obj_t *ui_VArEnergy;
extern lv_obj_t *ui_UniEnergy;
extern lv_obj_t *ui_ContTin;
extern lv_obj_t *ui_LabTin;
extern lv_obj_t *ui_VarTin;
extern lv_obj_t *ui_UnitTin;
extern lv_obj_t *ui_ContTout;
extern lv_obj_t *ui_LabTout;
extern lv_obj_t *ui_VarTout;
extern lv_obj_t *ui_UnitTout;
extern lv_obj_t *ui_PanlInput;
extern lv_obj_t *ui_LablInput;
extern lv_obj_t *ui_ContVin;
extern lv_obj_t *ui_LabVin;
extern lv_obj_t *ui_VarVin;
extern lv_obj_t *ui_UniVin;
extern lv_obj_t *ui_ContIin;
extern lv_obj_t *ui_LabIin;
extern lv_obj_t *ui_VarIin;
extern lv_obj_t *ui_UniIin;
extern lv_obj_t *ui_ContPin;
extern lv_obj_t *ui_LabPin;
extern lv_obj_t *ui_VarPin;
extern lv_obj_t *ui_UniPin;
extern lv_obj_t *ui_ContEffi;
extern lv_obj_t *ui_LabEffi;
extern lv_obj_t *ui_VarEffi;
extern lv_obj_t *ui_UniEffi;
extern lv_obj_t *ui_ContFin;
extern lv_obj_t *ui_LabFin;
extern lv_obj_t *ui_VarFin;
extern lv_obj_t *ui_UniFin;
extern lv_obj_t *ui_ScreenButtons;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Screen_Home;
extern lv_obj_t *uic_HomePanl1;
extern lv_obj_t *uic_Home_PanelOutputEnable;
extern lv_obj_t *uic_Home_SwitchEnableOutput;
extern lv_obj_t *uic_VarOutputState;
extern lv_obj_t *uic_PanlOutput;
extern lv_obj_t *uic_Output;
extern lv_obj_t *uic_VarVout;
extern lv_obj_t *uic_LabVout;
extern lv_obj_t *uic_VarVout;
extern lv_obj_t *uic_UniVout;
extern lv_obj_t *uic_ContIout;
extern lv_obj_t *uic_LabIout;
extern lv_obj_t *uic_VarIout;
extern lv_obj_t *uic_UniIout;
extern lv_obj_t *uic_ContPout;
extern lv_obj_t *uic_LabPout;
extern lv_obj_t *uic_VarPout;
extern lv_obj_t *uic_UniPout;
extern lv_obj_t *uic_ContEnergy;
extern lv_obj_t *uic_LabEnergy;
extern lv_obj_t *uic_VArEnergy;
extern lv_obj_t *uic_UniEnergy;
extern lv_obj_t *uic_ContTin;
extern lv_obj_t *uic_LabTin;
extern lv_obj_t *uic_VarTin;
extern lv_obj_t *uic_UnitTin;
extern lv_obj_t *uic_ContTout;
extern lv_obj_t *uic_LabTout;
extern lv_obj_t *uic_VarTout;
extern lv_obj_t *uic_UnitTout;
extern lv_obj_t *uic_PanlInput;
extern lv_obj_t *uic_LablInput;
extern lv_obj_t *uic_ContVin;
extern lv_obj_t *uic_VarVin;
extern lv_obj_t *uic_UniVin;
extern lv_obj_t *uic_ContIin;
extern lv_obj_t *uic_VarIin;
extern lv_obj_t *uic_UniIin;
extern lv_obj_t *uic_ContPin;
extern lv_obj_t *uic_LabPin;
extern lv_obj_t *uic_VarPin;
extern lv_obj_t *uic_UniPin;
extern lv_obj_t *uic_ContEffi;
extern lv_obj_t *uic_LabEffi;
extern lv_obj_t *uic_VarEffi;
extern lv_obj_t *uic_UniEffi;
extern lv_obj_t *uic_ContFin;
extern lv_obj_t *uic_LabFin;
extern lv_obj_t *uic_VarFin;
extern lv_obj_t *uic_UniFin;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

