// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_UniFin;
lv_obj_t *uic_VarFin;
lv_obj_t *uic_LabFin;
lv_obj_t *uic_ContFin;
lv_obj_t *uic_UniEffi;
lv_obj_t *uic_VarEffi;
lv_obj_t *uic_LabEffi;
lv_obj_t *uic_ContEffi;
lv_obj_t *uic_UniPin;
lv_obj_t *uic_VarPin;
lv_obj_t *uic_LabPin;
lv_obj_t *uic_ContPin;
lv_obj_t *uic_UniIin;
lv_obj_t *uic_VarIin;
lv_obj_t *uic_ContIin;
lv_obj_t *uic_UniVin;
lv_obj_t *uic_VarVin;
lv_obj_t *uic_ContVin;
lv_obj_t *uic_LablInput;
lv_obj_t *uic_PanlInput;
lv_obj_t *uic_UnitTout;
lv_obj_t *uic_VarTout;
lv_obj_t *uic_LabTout;
lv_obj_t *uic_ContTout;
lv_obj_t *uic_UnitTin;
lv_obj_t *uic_VarTin;
lv_obj_t *uic_LabTin;
lv_obj_t *uic_ContTin;
lv_obj_t *uic_UniEnergy;
lv_obj_t *uic_VArEnergy;
lv_obj_t *uic_LabEnergy;
lv_obj_t *uic_ContEnergy;
lv_obj_t *uic_UniPout;
lv_obj_t *uic_VarPout;
lv_obj_t *uic_LabPout;
lv_obj_t *uic_ContPout;
lv_obj_t *uic_UniIout;
lv_obj_t *uic_VarIout;
lv_obj_t *uic_LabIout;
lv_obj_t *uic_ContIout;
lv_obj_t *uic_UniVout;
lv_obj_t *uic_VarVout;
lv_obj_t *uic_LabVout;
lv_obj_t *uic_VarVout;
lv_obj_t *uic_Output;
lv_obj_t *uic_PanlOutput;
lv_obj_t *uic_VarOutputState;
lv_obj_t *uic_Home_SwitchEnableOutput;
lv_obj_t *uic_Home_PanelOutputEnable;
lv_obj_t *uic_HomePanl1;
lv_obj_t *uic_Screen_Home;
lv_obj_t *ui_Home = NULL;lv_obj_t *ui_HomePanl1 = NULL;lv_obj_t *ui_Home_PanelOutputEnable = NULL;lv_obj_t *ui_Home_SwitchEnableOutput = NULL;lv_obj_t *ui_VarOutputState = NULL;lv_obj_t *ui_PanlOutput = NULL;lv_obj_t *ui_Output = NULL;lv_obj_t *ui_ContVout = NULL;lv_obj_t *ui_LabVout = NULL;lv_obj_t *ui_VarVout = NULL;lv_obj_t *ui_UniVout = NULL;lv_obj_t *ui_ContIout = NULL;lv_obj_t *ui_LabIout = NULL;lv_obj_t *ui_VarIout = NULL;lv_obj_t *ui_UniIout = NULL;lv_obj_t *ui_ContPout = NULL;lv_obj_t *ui_LabPout = NULL;lv_obj_t *ui_VarPout = NULL;lv_obj_t *ui_UniPout = NULL;lv_obj_t *ui_ContEnergy = NULL;lv_obj_t *ui_LabEnergy = NULL;lv_obj_t *ui_VArEnergy = NULL;lv_obj_t *ui_UniEnergy = NULL;lv_obj_t *ui_ContTin = NULL;lv_obj_t *ui_LabTin = NULL;lv_obj_t *ui_VarTin = NULL;lv_obj_t *ui_UnitTin = NULL;lv_obj_t *ui_ContTout = NULL;lv_obj_t *ui_LabTout = NULL;lv_obj_t *ui_VarTout = NULL;lv_obj_t *ui_UnitTout = NULL;lv_obj_t *ui_PanlInput = NULL;lv_obj_t *ui_LablInput = NULL;lv_obj_t *ui_ContVin = NULL;lv_obj_t *ui_LabVin = NULL;lv_obj_t *ui_VarVin = NULL;lv_obj_t *ui_UniVin = NULL;lv_obj_t *ui_ContIin = NULL;lv_obj_t *ui_LabIin = NULL;lv_obj_t *ui_VarIin = NULL;lv_obj_t *ui_UniIin = NULL;lv_obj_t *ui_ContPin = NULL;lv_obj_t *ui_LabPin = NULL;lv_obj_t *ui_VarPin = NULL;lv_obj_t *ui_UniPin = NULL;lv_obj_t *ui_ContEffi = NULL;lv_obj_t *ui_LabEffi = NULL;lv_obj_t *ui_VarEffi = NULL;lv_obj_t *ui_UniEffi = NULL;lv_obj_t *ui_ContFin = NULL;lv_obj_t *ui_LabFin = NULL;lv_obj_t *ui_VarFin = NULL;lv_obj_t *ui_UniFin = NULL;lv_obj_t *ui_ScreenButtons = NULL;
// event funtions
void ui_event_Home_SwitchEnableOutput( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);lv_obj_t * target = lv_event_get_target(e);

if ( event_code == LV_EVENT_VALUE_CHANGED) {
      _ui_checked_set_text_value( ui_VarOutputState, target, "OUT: ON", "OUT: OFF");
}
}

// build funtions

void ui_Home_screen_init(void)
{
ui_Home = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_HomePanl1 = lv_obj_create(ui_Home);
lv_obj_set_width( ui_HomePanl1, lv_pct(98));
lv_obj_set_height( ui_HomePanl1, lv_pct(84));
lv_obj_set_align( ui_HomePanl1, LV_ALIGN_TOP_MID );

ui_Home_PanelOutputEnable = lv_obj_create(ui_HomePanl1);
lv_obj_set_height( ui_Home_PanelOutputEnable, 55);
lv_obj_set_width( ui_Home_PanelOutputEnable, lv_pct(98));
lv_obj_set_x( ui_Home_PanelOutputEnable, 0 );
lv_obj_set_y( ui_Home_PanelOutputEnable, -6 );
lv_obj_set_align( ui_Home_PanelOutputEnable, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_Home_PanelOutputEnable, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_Home_PanelOutputEnable, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BorderColorWidge);
ui_object_set_themeable_style_property(ui_Home_PanelOutputEnable, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BorderColorWidge);

ui_Home_SwitchEnableOutput = lv_switch_create(ui_Home_PanelOutputEnable);
lv_obj_set_width( ui_Home_SwitchEnableOutput, 134);
lv_obj_set_height( ui_Home_SwitchEnableOutput, 40);
lv_obj_set_align( ui_Home_SwitchEnableOutput, LV_ALIGN_RIGHT_MID );

lv_obj_set_style_bg_color(ui_Home_SwitchEnableOutput, lv_color_hex(0x40FF00), LV_PART_INDICATOR | LV_STATE_CHECKED );
lv_obj_set_style_bg_opa(ui_Home_SwitchEnableOutput, 255, LV_PART_INDICATOR| LV_STATE_CHECKED);

ui_VarOutputState = lv_label_create(ui_Home_PanelOutputEnable);
lv_obj_set_width( ui_VarOutputState, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarOutputState, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarOutputState, LV_ALIGN_LEFT_MID );
lv_label_set_text(ui_VarOutputState,"OUTPUT");
lv_obj_set_style_text_font(ui_VarOutputState, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanlOutput = lv_obj_create(ui_HomePanl1);
lv_obj_set_width( ui_PanlOutput, lv_pct(100));
lv_obj_set_height( ui_PanlOutput, lv_pct(55));
lv_obj_set_x( ui_PanlOutput, 0 );
lv_obj_set_y( ui_PanlOutput, 53 );
lv_obj_set_align( ui_PanlOutput, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_PanlOutput,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanlOutput, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanlOutput, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PanlOutput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BorderColorWidge);
ui_object_set_themeable_style_property(ui_PanlOutput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BorderColorWidge);

ui_Output = lv_label_create(ui_PanlOutput);
lv_obj_set_width( ui_Output, lv_pct(100));
lv_obj_set_height( ui_Output, LV_SIZE_CONTENT);   /// 17
lv_obj_set_x( ui_Output, 0 );
lv_obj_set_y( ui_Output, 3 );
lv_obj_set_align( ui_Output, LV_ALIGN_TOP_MID );
lv_label_set_text(ui_Output,"                  OUTPUT");
lv_obj_set_style_text_font(ui_Output, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContVout = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContVout);
lv_obj_set_width( ui_ContVout, lv_pct(100));
lv_obj_set_height( ui_ContVout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_ContVout, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContVout,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContVout, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContVout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContVout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContVout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContVout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabVout = lv_label_create(ui_ContVout);
lv_obj_set_width( ui_LabVout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabVout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabVout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabVout,"U");
lv_obj_set_style_text_font(ui_LabVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarVout = lv_label_create(ui_ContVout);
lv_obj_set_width( ui_VarVout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarVout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarVout, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarVout,"58.0");
lv_obj_set_style_text_font(ui_VarVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniVout = lv_label_create(ui_ContVout);
lv_obj_set_width( ui_UniVout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniVout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniVout, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniVout,"V");
lv_obj_set_style_text_font(ui_UniVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContIout = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContIout);
lv_obj_set_width( ui_ContIout, lv_pct(100));
lv_obj_set_height( ui_ContIout, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContIout, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContIout,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContIout, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContIout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContIout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContIout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContIout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabIout = lv_label_create(ui_ContIout);
lv_obj_set_width( ui_LabIout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabIout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabIout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabIout,"I");
lv_obj_set_style_text_font(ui_LabIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarIout = lv_label_create(ui_ContIout);
lv_obj_set_width( ui_VarIout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarIout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarIout, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarIout,"12.0");
lv_obj_set_style_text_font(ui_VarIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniIout = lv_label_create(ui_ContIout);
lv_obj_set_width( ui_UniIout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniIout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniIout, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniIout,"A");
lv_obj_set_style_text_font(ui_UniIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContPout = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContPout);
lv_obj_set_width( ui_ContPout, lv_pct(100));
lv_obj_set_height( ui_ContPout, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContPout, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContPout,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContPout, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContPout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContPout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContPout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContPout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabPout = lv_label_create(ui_ContPout);
lv_obj_set_width( ui_LabPout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabPout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabPout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabPout,"P");
lv_obj_set_style_text_font(ui_LabPout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarPout = lv_label_create(ui_ContPout);
lv_obj_set_width( ui_VarPout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarPout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarPout, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarPout,"512.3");
lv_obj_set_style_text_font(ui_VarPout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniPout = lv_label_create(ui_ContPout);
lv_obj_set_width( ui_UniPout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniPout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniPout, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniPout,"W");
lv_obj_set_style_text_font(ui_UniPout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContEnergy = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContEnergy);
lv_obj_set_width( ui_ContEnergy, lv_pct(100));
lv_obj_set_height( ui_ContEnergy, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContEnergy, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContEnergy,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContEnergy, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContEnergy, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContEnergy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContEnergy, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContEnergy, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabEnergy = lv_label_create(ui_ContEnergy);
lv_obj_set_width( ui_LabEnergy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabEnergy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabEnergy, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabEnergy,"E");
lv_obj_set_style_text_font(ui_LabEnergy, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VArEnergy = lv_label_create(ui_ContEnergy);
lv_obj_set_width( ui_VArEnergy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VArEnergy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VArEnergy, LV_ALIGN_CENTER );
lv_label_set_text(ui_VArEnergy,"879.23");
lv_obj_set_style_text_font(ui_VArEnergy, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniEnergy = lv_label_create(ui_ContEnergy);
lv_obj_set_width( ui_UniEnergy, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniEnergy, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniEnergy, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniEnergy,"Ah");
lv_obj_set_style_text_font(ui_UniEnergy, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContTin = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContTin);
lv_obj_set_width( ui_ContTin, lv_pct(100));
lv_obj_set_height( ui_ContTin, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContTin, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContTin,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContTin, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContTin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContTin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContTin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContTin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabTin = lv_label_create(ui_ContTin);
lv_obj_set_width( ui_LabTin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabTin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabTin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabTin,"T1");
lv_obj_set_style_text_font(ui_LabTin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarTin = lv_label_create(ui_ContTin);
lv_obj_set_width( ui_VarTin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarTin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarTin, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarTin,"55");
lv_obj_set_style_text_font(ui_VarTin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitTin = lv_label_create(ui_ContTin);
lv_obj_set_width( ui_UnitTin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UnitTin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UnitTin, LV_ALIGN_CENTER );
lv_label_set_text(ui_UnitTin,"C");
lv_obj_set_style_text_font(ui_UnitTin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContTout = lv_obj_create(ui_PanlOutput);
lv_obj_remove_style_all(ui_ContTout);
lv_obj_set_width( ui_ContTout, lv_pct(100));
lv_obj_set_height( ui_ContTout, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContTout, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContTout,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContTout, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContTout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContTout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContTout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContTout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabTout = lv_label_create(ui_ContTout);
lv_obj_set_width( ui_LabTout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabTout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabTout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabTout,"T2");
lv_obj_set_style_text_font(ui_LabTout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarTout = lv_label_create(ui_ContTout);
lv_obj_set_width( ui_VarTout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarTout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarTout, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarTout,"89");
lv_obj_set_style_text_font(ui_VarTout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UnitTout = lv_label_create(ui_ContTout);
lv_obj_set_width( ui_UnitTout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UnitTout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UnitTout, LV_ALIGN_CENTER );
lv_label_set_text(ui_UnitTout,"C");
lv_obj_set_style_text_font(ui_UnitTout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_PanlInput = lv_obj_create(ui_HomePanl1);
lv_obj_set_width( ui_PanlInput, lv_pct(100));
lv_obj_set_height( ui_PanlInput, lv_pct(70));
lv_obj_set_x( ui_PanlInput, 0 );
lv_obj_set_y( ui_PanlInput, 150 );
lv_obj_set_align( ui_PanlInput, LV_ALIGN_BOTTOM_MID );
lv_obj_set_flex_flow(ui_PanlInput,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanlInput, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanlInput, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PanlInput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BorderColorWidge);
ui_object_set_themeable_style_property(ui_PanlInput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BorderColorWidge);

ui_LablInput = lv_label_create(ui_PanlInput);
lv_obj_set_width( ui_LablInput, lv_pct(100));
lv_obj_set_height( ui_LablInput, LV_SIZE_CONTENT);   /// 10
lv_obj_set_align( ui_LablInput, LV_ALIGN_CENTER );
lv_label_set_text(ui_LablInput,"                   INPUT");
lv_obj_set_style_text_font(ui_LablInput, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContVin = lv_obj_create(ui_PanlInput);
lv_obj_remove_style_all(ui_ContVin);
lv_obj_set_width( ui_ContVin, lv_pct(100));
lv_obj_set_height( ui_ContVin, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContVin, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContVin,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContVin, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContVin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContVin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContVin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContVin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabVin = lv_label_create(ui_ContVin);
lv_obj_set_width( ui_LabVin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabVin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabVin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabVin,"u");
lv_obj_set_style_text_font(ui_LabVin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarVin = lv_label_create(ui_ContVin);
lv_obj_set_width( ui_VarVin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarVin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarVin, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarVin,"232.3");
lv_obj_set_style_text_font(ui_VarVin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniVin = lv_label_create(ui_ContVin);
lv_obj_set_width( ui_UniVin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniVin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniVin, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniVin,"V");
lv_obj_set_style_text_font(ui_UniVin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContIin = lv_obj_create(ui_PanlInput);
lv_obj_remove_style_all(ui_ContIin);
lv_obj_set_width( ui_ContIin, lv_pct(100));
lv_obj_set_height( ui_ContIin, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContIin, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContIin,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContIin, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContIin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContIin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContIin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContIin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabIin = lv_label_create(ui_ContIin);
lv_obj_set_width( ui_LabIin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabIin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabIin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabIin,"i");
lv_obj_set_style_text_font(ui_LabIin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarIin = lv_label_create(ui_ContIin);
lv_obj_set_width( ui_VarIin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarIin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarIin, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarIin,"1.2");
lv_obj_set_style_text_font(ui_VarIin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniIin = lv_label_create(ui_ContIin);
lv_obj_set_width( ui_UniIin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniIin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniIin, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniIin,"A");
lv_obj_set_style_text_font(ui_UniIin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContPin = lv_obj_create(ui_PanlInput);
lv_obj_remove_style_all(ui_ContPin);
lv_obj_set_width( ui_ContPin, lv_pct(100));
lv_obj_set_height( ui_ContPin, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContPin, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContPin,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContPin, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContPin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContPin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContPin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContPin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabPin = lv_label_create(ui_ContPin);
lv_obj_set_width( ui_LabPin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabPin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabPin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabPin,"p");
lv_obj_set_style_text_font(ui_LabPin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarPin = lv_label_create(ui_ContPin);
lv_obj_set_width( ui_VarPin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarPin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarPin, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarPin,"870");
lv_obj_set_style_text_font(ui_VarPin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniPin = lv_label_create(ui_ContPin);
lv_obj_set_width( ui_UniPin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniPin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniPin, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniPin,"W");
lv_obj_set_style_text_font(ui_UniPin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContEffi = lv_obj_create(ui_PanlInput);
lv_obj_remove_style_all(ui_ContEffi);
lv_obj_set_width( ui_ContEffi, lv_pct(100));
lv_obj_set_height( ui_ContEffi, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContEffi, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContEffi,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContEffi, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContEffi, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContEffi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContEffi, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContEffi, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabEffi = lv_label_create(ui_ContEffi);
lv_obj_set_width( ui_LabEffi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabEffi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabEffi, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabEffi,"E");
lv_obj_set_style_text_font(ui_LabEffi, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarEffi = lv_label_create(ui_ContEffi);
lv_obj_set_width( ui_VarEffi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarEffi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarEffi, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarEffi,"98.9");
lv_obj_set_style_text_font(ui_VarEffi, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniEffi = lv_label_create(ui_ContEffi);
lv_obj_set_width( ui_UniEffi, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniEffi, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniEffi, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniEffi,"%");
lv_obj_set_style_text_font(ui_UniEffi, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContFin = lv_obj_create(ui_PanlInput);
lv_obj_remove_style_all(ui_ContFin);
lv_obj_set_width( ui_ContFin, lv_pct(100));
lv_obj_set_height( ui_ContFin, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContFin, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_ContFin,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ContFin, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_ContFin, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContFin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContFin, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContFin, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabFin = lv_label_create(ui_ContFin);
lv_obj_set_width( ui_LabFin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabFin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabFin, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabFin,"f");
lv_obj_set_style_text_font(ui_LabFin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarFin = lv_label_create(ui_ContFin);
lv_obj_set_width( ui_VarFin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VarFin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VarFin, LV_ALIGN_CENTER );
lv_label_set_text(ui_VarFin,"50.1");
lv_obj_set_style_text_font(ui_VarFin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniFin = lv_label_create(ui_ContFin);
lv_obj_set_width( ui_UniFin, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniFin, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_UniFin, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniFin,"Hz");
lv_obj_set_style_text_font(ui_UniFin, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ScreenButtons = ui_ScreenButtons_create(ui_Home);
lv_obj_set_x( ui_ScreenButtons, 0 );
lv_obj_set_y( ui_ScreenButtons, -2 );

lv_obj_add_event_cb(ui_Home_SwitchEnableOutput, ui_event_Home_SwitchEnableOutput, LV_EVENT_ALL, NULL);
uic_Screen_Home = ui_Home;
uic_HomePanl1 = ui_HomePanl1;
uic_Home_PanelOutputEnable = ui_Home_PanelOutputEnable;
uic_Home_SwitchEnableOutput = ui_Home_SwitchEnableOutput;
uic_VarOutputState = ui_VarOutputState;
uic_PanlOutput = ui_PanlOutput;
uic_Output = ui_Output;
uic_VarVout = ui_ContVout;
uic_LabVout = ui_LabVout;
uic_VarVout = ui_VarVout;
uic_UniVout = ui_UniVout;
uic_ContIout = ui_ContIout;
uic_LabIout = ui_LabIout;
uic_VarIout = ui_VarIout;
uic_UniIout = ui_UniIout;
uic_ContPout = ui_ContPout;
uic_LabPout = ui_LabPout;
uic_VarPout = ui_VarPout;
uic_UniPout = ui_UniPout;
uic_ContEnergy = ui_ContEnergy;
uic_LabEnergy = ui_LabEnergy;
uic_VArEnergy = ui_VArEnergy;
uic_UniEnergy = ui_UniEnergy;
uic_ContTin = ui_ContTin;
uic_LabTin = ui_LabTin;
uic_VarTin = ui_VarTin;
uic_UnitTin = ui_UnitTin;
uic_ContTout = ui_ContTout;
uic_LabTout = ui_LabTout;
uic_VarTout = ui_VarTout;
uic_UnitTout = ui_UnitTout;
uic_PanlInput = ui_PanlInput;
uic_LablInput = ui_LablInput;
uic_ContVin = ui_ContVin;
uic_VarVin = ui_VarVin;
uic_UniVin = ui_UniVin;
uic_ContIin = ui_ContIin;
uic_VarIin = ui_VarIin;
uic_UniIin = ui_UniIin;
uic_ContPin = ui_ContPin;
uic_LabPin = ui_LabPin;
uic_VarPin = ui_VarPin;
uic_UniPin = ui_UniPin;
uic_ContEffi = ui_ContEffi;
uic_LabEffi = ui_LabEffi;
uic_VarEffi = ui_VarEffi;
uic_UniEffi = ui_UniEffi;
uic_ContFin = ui_ContFin;
uic_LabFin = ui_LabFin;
uic_VarFin = ui_VarFin;
uic_UniFin = ui_UniFin;

}

void ui_Home_screen_destroy(void)
{
   if (ui_Home) lv_obj_del(ui_Home);

// NULL screen variables
uic_Screen_Home= NULL;
ui_Home= NULL;
uic_HomePanl1= NULL;
ui_HomePanl1= NULL;
uic_Home_PanelOutputEnable= NULL;
ui_Home_PanelOutputEnable= NULL;
uic_Home_SwitchEnableOutput= NULL;
ui_Home_SwitchEnableOutput= NULL;
uic_VarOutputState= NULL;
ui_VarOutputState= NULL;
uic_PanlOutput= NULL;
ui_PanlOutput= NULL;
uic_Output= NULL;
ui_Output= NULL;
uic_VarVout= NULL;
ui_ContVout= NULL;
uic_LabVout= NULL;
ui_LabVout= NULL;
uic_VarVout= NULL;
ui_VarVout= NULL;
uic_UniVout= NULL;
ui_UniVout= NULL;
uic_ContIout= NULL;
ui_ContIout= NULL;
uic_LabIout= NULL;
ui_LabIout= NULL;
uic_VarIout= NULL;
ui_VarIout= NULL;
uic_UniIout= NULL;
ui_UniIout= NULL;
uic_ContPout= NULL;
ui_ContPout= NULL;
uic_LabPout= NULL;
ui_LabPout= NULL;
uic_VarPout= NULL;
ui_VarPout= NULL;
uic_UniPout= NULL;
ui_UniPout= NULL;
uic_ContEnergy= NULL;
ui_ContEnergy= NULL;
uic_LabEnergy= NULL;
ui_LabEnergy= NULL;
uic_VArEnergy= NULL;
ui_VArEnergy= NULL;
uic_UniEnergy= NULL;
ui_UniEnergy= NULL;
uic_ContTin= NULL;
ui_ContTin= NULL;
uic_LabTin= NULL;
ui_LabTin= NULL;
uic_VarTin= NULL;
ui_VarTin= NULL;
uic_UnitTin= NULL;
ui_UnitTin= NULL;
uic_ContTout= NULL;
ui_ContTout= NULL;
uic_LabTout= NULL;
ui_LabTout= NULL;
uic_VarTout= NULL;
ui_VarTout= NULL;
uic_UnitTout= NULL;
ui_UnitTout= NULL;
uic_PanlInput= NULL;
ui_PanlInput= NULL;
uic_LablInput= NULL;
ui_LablInput= NULL;
uic_ContVin= NULL;
ui_ContVin= NULL;
ui_LabVin= NULL;
uic_VarVin= NULL;
ui_VarVin= NULL;
uic_UniVin= NULL;
ui_UniVin= NULL;
uic_ContIin= NULL;
ui_ContIin= NULL;
ui_LabIin= NULL;
uic_VarIin= NULL;
ui_VarIin= NULL;
uic_UniIin= NULL;
ui_UniIin= NULL;
uic_ContPin= NULL;
ui_ContPin= NULL;
uic_LabPin= NULL;
ui_LabPin= NULL;
uic_VarPin= NULL;
ui_VarPin= NULL;
uic_UniPin= NULL;
ui_UniPin= NULL;
uic_ContEffi= NULL;
ui_ContEffi= NULL;
uic_LabEffi= NULL;
ui_LabEffi= NULL;
uic_VarEffi= NULL;
ui_VarEffi= NULL;
uic_UniEffi= NULL;
ui_UniEffi= NULL;
uic_ContFin= NULL;
ui_ContFin= NULL;
uic_LabFin= NULL;
ui_LabFin= NULL;
uic_VarFin= NULL;
ui_VarFin= NULL;
uic_UniFin= NULL;
ui_UniFin= NULL;
ui_ScreenButtons= NULL;

}
