// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETTINGS_H
#define UI_SETTINGS_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Settings
extern void ui_Settings_screen_init(void);
extern void ui_Settings_screen_destroy(void);
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_ScreenButtons3;
extern lv_obj_t *ui_PanelBrightness;
extern lv_obj_t *ui_VarBrightness;
extern void ui_event_SliderBrightness( lv_event_t * e);
extern lv_obj_t *ui_SliderBrightness;
extern void ui_event_VarSleepTimer( lv_event_t * e);
extern lv_obj_t *ui_VarSleepTimer;
extern void ui_event_SliderSleepTimer( lv_event_t * e);
extern lv_obj_t *ui_SliderSleepTimer;
extern lv_obj_t *ui_Settings_DropdownFanControll;
extern lv_obj_t *ui_Settings_TextAreaLogs;
extern lv_obj_t *ui_ButtonResetEnergy;
extern lv_obj_t *ui_LabelResetEnergy;
// CUSTOM VARIABLES
extern lv_obj_t *uic_Settings;
extern lv_obj_t *uic_PanelBrightness;
extern lv_obj_t *uic_VarBrightness;
extern lv_obj_t *uic_SliderBrightness;
extern lv_obj_t *uic_VarSleepTimer;
extern lv_obj_t *uic_SliderSleepTimer;
extern lv_obj_t *uic_Settings_DropdownFanControll;
extern lv_obj_t *uic_Settings_TextAreaLogs;
extern lv_obj_t *uic_ButtonResetEnergy;
extern lv_obj_t *uic_LabelResetEnergy;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

