// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SETVALUES_H
#define UI_SETVALUES_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_SetValues
extern void ui_SetValues_screen_init(void);
extern void ui_SetValues_screen_destroy(void);
extern lv_obj_t *ui_SetValues;
extern lv_obj_t *ui_ScreenButtons2;
extern lv_obj_t *ui_PanlSetOnlineOutput;
extern lv_obj_t *ui_LablSetOnlineOutput;
extern lv_obj_t *ui_LablSetOnlineOutput1;
extern lv_obj_t *ui_ContSetOnVout;
extern lv_obj_t *ui_LabSetOnVout;
extern void ui_event_VarOnlineVout( lv_event_t * e);
extern lv_obj_t *ui_VarOnlineVout;
extern void ui_event_VarOfflineVout( lv_event_t * e);
extern lv_obj_t *ui_VarOfflineVout;
extern lv_obj_t *ui_UniVout1;
extern lv_obj_t *ui_ContSetOnIout;
extern lv_obj_t *ui_LabSetOnIout;
extern void ui_event_VarOnlineIout( lv_event_t * e);
extern lv_obj_t *ui_VarOnlineIout;
extern void ui_event_VarOfflineIout( lv_event_t * e);
extern lv_obj_t *ui_VarOfflineIout;
extern lv_obj_t *ui_UniIout1;
extern lv_obj_t *ui_SetValues_TextArea2;
extern void ui_event_Numpad( lv_event_t * e);
extern lv_obj_t *ui_Numpad;
extern lv_obj_t *ui_SetValues_PanelTimer;
extern lv_obj_t *ui_SetValues_Label1;
extern void ui_event_SetValues_TextAreaTimer( lv_event_t * e);
extern lv_obj_t *ui_SetValues_TextAreaTimer;
extern lv_obj_t *ui_SetValues_SwitchTimer;
// CUSTOM VARIABLES
extern lv_obj_t *uic_SetValues;
extern lv_obj_t *uic_PanlSetOnlineOutput;
extern lv_obj_t *uic_LablSetOnlineOutput;
extern lv_obj_t *uic_ContSetOnVout;
extern lv_obj_t *uic_LabSetOnVout;
extern lv_obj_t *uic_VarOnlineVout;
extern lv_obj_t *uic_VarOfflineVout;
extern lv_obj_t *uic_UniVout1;
extern lv_obj_t *uic_ContSetOnIout;
extern lv_obj_t *uic_LabSetOnIout;
extern lv_obj_t *uic_VarOnlineIout;
extern lv_obj_t *uic_VarOfflineIout;
extern lv_obj_t *uic_UniIout1;
extern lv_obj_t *uic_Numpad;
extern lv_obj_t *uic_SetValues_PanelTimer;
extern lv_obj_t *uic_SetValues_TextAreaTimer;
extern lv_obj_t *uic_SetValues_SwitchTimer;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

