// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"

lv_obj_t *uic_SetValues_SwitchTimer;
lv_obj_t *uic_SetValues_TextAreaTimer;
lv_obj_t *uic_SetValues_PanelTimer;
lv_obj_t *uic_Numpad;
lv_obj_t *uic_UniIout1;
lv_obj_t *uic_VarOfflineIout;
lv_obj_t *uic_VarOnlineIout;
lv_obj_t *uic_LabSetOnIout;
lv_obj_t *uic_ContSetOnIout;
lv_obj_t *uic_UniVout1;
lv_obj_t *uic_VarOfflineVout;
lv_obj_t *uic_VarOnlineVout;
lv_obj_t *uic_LabSetOnVout;
lv_obj_t *uic_ContSetOnVout;
lv_obj_t *uic_LablSetOnlineOutput;
lv_obj_t *uic_PanlSetOnlineOutput;
lv_obj_t *uic_SetValues;
lv_obj_t *ui_SetValues = NULL;lv_obj_t *ui_ScreenButtons2 = NULL;lv_obj_t *ui_PanlSetOnlineOutput = NULL;lv_obj_t *ui_LablSetOnlineOutput = NULL;lv_obj_t *ui_LablSetOnlineOutput1 = NULL;lv_obj_t *ui_ContSetOnVout = NULL;lv_obj_t *ui_LabSetOnVout = NULL;lv_obj_t *ui_VarOnlineVout = NULL;lv_obj_t *ui_VarOfflineVout = NULL;lv_obj_t *ui_UniVout1 = NULL;lv_obj_t *ui_ContSetOnIout = NULL;lv_obj_t *ui_LabSetOnIout = NULL;lv_obj_t *ui_VarOnlineIout = NULL;lv_obj_t *ui_VarOfflineIout = NULL;lv_obj_t *ui_UniIout1 = NULL;lv_obj_t *ui_SetValues_TextArea2 = NULL;lv_obj_t *ui_Numpad = NULL;lv_obj_t *ui_SetValues_PanelTimer = NULL;lv_obj_t *ui_SetValues_Label1 = NULL;lv_obj_t *ui_SetValues_TextAreaTimer = NULL;lv_obj_t *ui_SetValues_SwitchTimer = NULL;
// event funtions
void ui_event_VarOnlineVout( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Numpad,  ui_VarOnlineVout);
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_VarOfflineVout( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Numpad,  ui_VarOfflineVout);
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_VarOnlineIout( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Numpad,  ui_VarOnlineIout);
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_VarOfflineIout( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Numpad,  ui_VarOfflineIout);
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

void ui_event_Numpad( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_READY) {
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_ADD);
}
}

void ui_event_SetValues_TextAreaTimer( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_CLICKED) {
      _ui_keyboard_set_target(ui_Numpad,  ui_SetValues_TextAreaTimer);
      _ui_flag_modify( ui_Numpad, LV_OBJ_FLAG_HIDDEN, _UI_MODIFY_FLAG_REMOVE);
}
}

// build funtions

void ui_SetValues_screen_init(void)
{
ui_SetValues = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SetValues, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_ScreenButtons2 = ui_ScreenButtons_create(ui_SetValues);
lv_obj_set_x( ui_ScreenButtons2, 0 );
lv_obj_set_y( ui_ScreenButtons2, -2 );

ui_PanlSetOnlineOutput = lv_obj_create(ui_SetValues);
lv_obj_set_width( ui_PanlSetOnlineOutput, lv_pct(100));
lv_obj_set_height( ui_PanlSetOnlineOutput, lv_pct(31));
lv_obj_set_align( ui_PanlSetOnlineOutput, LV_ALIGN_TOP_MID );
lv_obj_set_flex_flow(ui_PanlSetOnlineOutput,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_PanlSetOnlineOutput, LV_FLEX_ALIGN_SPACE_AROUND, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_PanlSetOnlineOutput, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_PanlSetOnlineOutput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BorderColorWidge);
ui_object_set_themeable_style_property(ui_PanlSetOnlineOutput, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BorderColorWidge);

ui_LablSetOnlineOutput = lv_label_create(ui_PanlSetOnlineOutput);
lv_obj_set_width( ui_LablSetOnlineOutput, lv_pct(62));
lv_obj_set_height( ui_LablSetOnlineOutput, LV_SIZE_CONTENT);   /// 10
lv_obj_set_x( ui_LablSetOnlineOutput, 1 );
lv_obj_set_y( ui_LablSetOnlineOutput, -48 );
lv_obj_set_align( ui_LablSetOnlineOutput, LV_ALIGN_CENTER );
lv_label_set_text(ui_LablSetOnlineOutput,"   SET  OUTPUTS");
lv_obj_set_style_text_font(ui_LablSetOnlineOutput, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LablSetOnlineOutput1 = lv_label_create(ui_PanlSetOnlineOutput);
lv_obj_set_width( ui_LablSetOnlineOutput1, lv_pct(100));
lv_obj_set_height( ui_LablSetOnlineOutput1, LV_SIZE_CONTENT);   /// 10
lv_obj_set_align( ui_LablSetOnlineOutput1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LablSetOnlineOutput1,"              ONLINE      OFFLINE");
lv_obj_set_style_text_font(ui_LablSetOnlineOutput1, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContSetOnVout = lv_obj_create(ui_PanlSetOnlineOutput);
lv_obj_remove_style_all(ui_ContSetOnVout);
lv_obj_set_width( ui_ContSetOnVout, lv_pct(100));
lv_obj_set_height( ui_ContSetOnVout, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContSetOnVout, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ContSetOnVout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContSetOnVout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContSetOnVout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContSetOnVout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabSetOnVout = lv_label_create(ui_ContSetOnVout);
lv_obj_set_width( ui_LabSetOnVout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabSetOnVout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabSetOnVout, -120 );
lv_obj_set_y( ui_LabSetOnVout, 0 );
lv_obj_set_align( ui_LabSetOnVout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabSetOnVout,"U");
lv_obj_set_style_text_font(ui_LabSetOnVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarOnlineVout = lv_textarea_create(ui_ContSetOnVout);
lv_obj_set_width( ui_VarOnlineVout, 98);
lv_obj_set_height( ui_VarOnlineVout, LV_SIZE_CONTENT);   /// 50
lv_obj_set_x( ui_VarOnlineVout, -40 );
lv_obj_set_y( ui_VarOnlineVout, 0 );
lv_obj_set_align( ui_VarOnlineVout, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_VarOnlineVout,5);
lv_textarea_set_text(ui_VarOnlineVout,"48.0");
lv_textarea_set_one_line(ui_VarOnlineVout,true);
lv_obj_set_style_text_font(ui_VarOnlineVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VarOnlineVout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VarOnlineVout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarOfflineVout = lv_textarea_create(ui_ContSetOnVout);
lv_obj_set_width( ui_VarOfflineVout, 98);
lv_obj_set_height( ui_VarOfflineVout, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_VarOfflineVout, 68 );
lv_obj_set_y( ui_VarOfflineVout, 0 );
lv_obj_set_align( ui_VarOfflineVout, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_VarOfflineVout,5);
lv_textarea_set_text(ui_VarOfflineVout,"48.0");
lv_textarea_set_one_line(ui_VarOfflineVout,true);
lv_obj_set_style_text_font(ui_VarOfflineVout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VarOfflineVout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VarOfflineVout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniVout1 = lv_label_create(ui_ContSetOnVout);
lv_obj_set_width( ui_UniVout1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniVout1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UniVout1, 136 );
lv_obj_set_y( ui_UniVout1, 0 );
lv_obj_set_align( ui_UniVout1, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniVout1,"V");
lv_obj_set_style_text_font(ui_UniVout1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ContSetOnIout = lv_obj_create(ui_PanlSetOnlineOutput);
lv_obj_remove_style_all(ui_ContSetOnIout);
lv_obj_set_width( ui_ContSetOnIout, lv_pct(100));
lv_obj_set_height( ui_ContSetOnIout, LV_SIZE_CONTENT);   /// 30
lv_obj_set_align( ui_ContSetOnIout, LV_ALIGN_TOP_MID );
lv_obj_clear_flag( ui_ContSetOnIout, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
ui_object_set_themeable_style_property(ui_ContSetOnIout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_COLOR, _ui_theme_color_BordercolorText);
ui_object_set_themeable_style_property(ui_ContSetOnIout, LV_PART_MAIN| LV_STATE_DEFAULT, LV_STYLE_BORDER_OPA, _ui_theme_alpha_BordercolorText);
lv_obj_set_style_border_width(ui_ContSetOnIout, 1, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabSetOnIout = lv_label_create(ui_ContSetOnIout);
lv_obj_set_width( ui_LabSetOnIout, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabSetOnIout, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabSetOnIout, -120 );
lv_obj_set_y( ui_LabSetOnIout, 0 );
lv_obj_set_align( ui_LabSetOnIout, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabSetOnIout,"I");
lv_obj_set_style_text_font(ui_LabSetOnIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarOnlineIout = lv_textarea_create(ui_ContSetOnIout);
lv_obj_set_width( ui_VarOnlineIout, 98);
lv_obj_set_height( ui_VarOnlineIout, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_VarOnlineIout, -40 );
lv_obj_set_y( ui_VarOnlineIout, 0 );
lv_obj_set_align( ui_VarOnlineIout, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_VarOnlineIout,5);
lv_textarea_set_text(ui_VarOnlineIout,"20");
lv_textarea_set_one_line(ui_VarOnlineIout,true);
lv_obj_set_style_text_font(ui_VarOnlineIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VarOnlineIout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VarOnlineIout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VarOfflineIout = lv_textarea_create(ui_ContSetOnIout);
lv_obj_set_width( ui_VarOfflineIout, 98);
lv_obj_set_height( ui_VarOfflineIout, LV_SIZE_CONTENT);   /// 60
lv_obj_set_x( ui_VarOfflineIout, 68 );
lv_obj_set_y( ui_VarOfflineIout, 0 );
lv_obj_set_align( ui_VarOfflineIout, LV_ALIGN_CENTER );
lv_textarea_set_max_length(ui_VarOfflineIout,5);
lv_textarea_set_text(ui_VarOfflineIout,"10");
lv_textarea_set_one_line(ui_VarOfflineIout,true);
lv_obj_set_style_text_font(ui_VarOfflineIout, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_VarOfflineIout, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_VarOfflineIout, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_UniIout1 = lv_label_create(ui_ContSetOnIout);
lv_obj_set_width( ui_UniIout1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_UniIout1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_UniIout1, 136 );
lv_obj_set_y( ui_UniIout1, 0 );
lv_obj_set_align( ui_UniIout1, LV_ALIGN_CENTER );
lv_label_set_text(ui_UniIout1,"A");
lv_obj_set_style_text_font(ui_UniIout1, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetValues_TextArea2 = lv_textarea_create(ui_SetValues);
lv_obj_set_width( ui_SetValues_TextArea2, lv_pct(98));
lv_obj_set_height( ui_SetValues_TextArea2, lv_pct(42));
lv_obj_set_x( ui_SetValues_TextArea2, 0 );
lv_obj_set_y( ui_SetValues_TextArea2, -80 );
lv_obj_set_align( ui_SetValues_TextArea2, LV_ALIGN_BOTTOM_MID );
lv_textarea_set_text(ui_SetValues_TextArea2,"		        Online Outputs:\nV:		41.5 - 58.5V in 0.1V steps\nI: 		0 - 75A in 0.1A steps\n\n		       Offline Outputs:\nV: 	48 - 58.5V in 0.1V steps\nI: 		0 - 75A in 0.1A steps\n");
lv_obj_set_style_text_font(ui_SetValues_TextArea2, &lv_font_montserrat_18, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Numpad = lv_keyboard_create(ui_SetValues);
lv_keyboard_set_mode(ui_Numpad,LV_KEYBOARD_MODE_NUMBER);
lv_obj_set_width( ui_Numpad, 309);
lv_obj_set_height( ui_Numpad, 205);
lv_obj_set_x( ui_Numpad, 0 );
lv_obj_set_y( ui_Numpad, -80 );
lv_obj_set_align( ui_Numpad, LV_ALIGN_BOTTOM_MID );
lv_obj_add_flag( ui_Numpad, LV_OBJ_FLAG_HIDDEN );   /// Flags

lv_obj_set_style_radius(ui_Numpad, 10, LV_PART_ITEMS| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Numpad, &lv_font_montserrat_20, LV_PART_ITEMS| LV_STATE_DEFAULT);

ui_SetValues_PanelTimer = lv_obj_create(ui_SetValues);
lv_obj_set_height( ui_SetValues_PanelTimer, 44);
lv_obj_set_width( ui_SetValues_PanelTimer, lv_pct(98));
lv_obj_set_x( ui_SetValues_PanelTimer, 0 );
lv_obj_set_y( ui_SetValues_PanelTimer, -67 );
lv_obj_set_align( ui_SetValues_PanelTimer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SetValues_PanelTimer,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_SetValues_PanelTimer, LV_FLEX_ALIGN_SPACE_BETWEEN, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_SetValues_PanelTimer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_SetValues_Label1 = lv_label_create(ui_SetValues_PanelTimer);
lv_obj_set_width( ui_SetValues_Label1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetValues_Label1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_SetValues_Label1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetValues_Label1,"Timer:");

ui_SetValues_TextAreaTimer = lv_textarea_create(ui_SetValues_PanelTimer);
lv_obj_set_width( ui_SetValues_TextAreaTimer, 150);
lv_obj_set_height( ui_SetValues_TextAreaTimer, LV_SIZE_CONTENT);   /// 70
lv_obj_set_align( ui_SetValues_TextAreaTimer, LV_ALIGN_CENTER );
lv_textarea_set_placeholder_text(ui_SetValues_TextAreaTimer,"HH.MM.SS");
lv_textarea_set_one_line(ui_SetValues_TextAreaTimer,true);
lv_obj_set_style_outline_color(ui_SetValues_TextAreaTimer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_outline_opa(ui_SetValues_TextAreaTimer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_width(ui_SetValues_TextAreaTimer, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_outline_pad(ui_SetValues_TextAreaTimer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetValues_SwitchTimer = lv_switch_create(ui_SetValues_PanelTimer);
lv_obj_set_width( ui_SetValues_SwitchTimer, 67);
lv_obj_set_height( ui_SetValues_SwitchTimer, 25);
lv_obj_set_align( ui_SetValues_SwitchTimer, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_VarOnlineVout, ui_event_VarOnlineVout, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VarOfflineVout, ui_event_VarOfflineVout, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VarOnlineIout, ui_event_VarOnlineIout, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_VarOfflineIout, ui_event_VarOfflineIout, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_Numpad, ui_event_Numpad, LV_EVENT_ALL, NULL);
lv_obj_add_event_cb(ui_SetValues_TextAreaTimer, ui_event_SetValues_TextAreaTimer, LV_EVENT_ALL, NULL);
uic_SetValues = ui_SetValues;
uic_PanlSetOnlineOutput = ui_PanlSetOnlineOutput;
uic_LablSetOnlineOutput = ui_LablSetOnlineOutput;
uic_ContSetOnVout = ui_ContSetOnVout;
uic_LabSetOnVout = ui_LabSetOnVout;
uic_VarOnlineVout = ui_VarOnlineVout;
uic_VarOfflineVout = ui_VarOfflineVout;
uic_UniVout1 = ui_UniVout1;
uic_ContSetOnIout = ui_ContSetOnIout;
uic_LabSetOnIout = ui_LabSetOnIout;
uic_VarOnlineIout = ui_VarOnlineIout;
uic_VarOfflineIout = ui_VarOfflineIout;
uic_UniIout1 = ui_UniIout1;
uic_Numpad = ui_Numpad;
uic_SetValues_PanelTimer = ui_SetValues_PanelTimer;
uic_SetValues_TextAreaTimer = ui_SetValues_TextAreaTimer;
uic_SetValues_SwitchTimer = ui_SetValues_SwitchTimer;

}

void ui_SetValues_screen_destroy(void)
{
   if (ui_SetValues) lv_obj_del(ui_SetValues);

// NULL screen variables
uic_SetValues= NULL;
ui_SetValues= NULL;
ui_ScreenButtons2= NULL;
uic_PanlSetOnlineOutput= NULL;
ui_PanlSetOnlineOutput= NULL;
uic_LablSetOnlineOutput= NULL;
ui_LablSetOnlineOutput= NULL;
ui_LablSetOnlineOutput1= NULL;
uic_ContSetOnVout= NULL;
ui_ContSetOnVout= NULL;
uic_LabSetOnVout= NULL;
ui_LabSetOnVout= NULL;
uic_VarOnlineVout= NULL;
ui_VarOnlineVout= NULL;
uic_VarOfflineVout= NULL;
ui_VarOfflineVout= NULL;
uic_UniVout1= NULL;
ui_UniVout1= NULL;
uic_ContSetOnIout= NULL;
ui_ContSetOnIout= NULL;
uic_LabSetOnIout= NULL;
ui_LabSetOnIout= NULL;
uic_VarOnlineIout= NULL;
ui_VarOnlineIout= NULL;
uic_VarOfflineIout= NULL;
ui_VarOfflineIout= NULL;
uic_UniIout1= NULL;
ui_UniIout1= NULL;
ui_SetValues_TextArea2= NULL;
uic_Numpad= NULL;
ui_Numpad= NULL;
uic_SetValues_PanelTimer= NULL;
ui_SetValues_PanelTimer= NULL;
ui_SetValues_Label1= NULL;
uic_SetValues_TextAreaTimer= NULL;
ui_SetValues_TextAreaTimer= NULL;
uic_SetValues_SwitchTimer= NULL;
ui_SetValues_SwitchTimer= NULL;

}
